### PR TITLE
iDeep integration in Linear/Convolution/Deconvolution/ReLU (for review).

### PR DESCRIPTION
**Pull request by fengyuan14**
Hi, niboshi

This is our PR about latest `iDeep` integration. Please review.

In addition, let me show you how to reference `iDeep` for now,
1. For now, you can only reference Intel Chainer to get `iDeep`. The repo includes `iDeep` package. We will post a new release of Intel Chainer by the end of this week (WW3 2018). The release includes latest `iDeep`.
2. `iDeep` open source (github) needs Intel internal security process, which is work-in-progress.
3. About `pip install iDeep`. The function needs Intel internal security/confidential approval either. It is work-in-progress.

Thanks.

### CODE REVIEW

**Comment by niboshi** [comment]
Thank you for PR!
By "Intel Chainer", do you mean https://github.com/intel/chainer? I can't find the ideep package there.

**Comment by fengyuan14** [comment]
Yes, I just mean https://github.com/intel/chainer.

We have not delivered the latest release yet. `iDeep` package in older version is the directory of `INTEL_CHAINER_ROOT/dnn`. We will have a release by the end of this week (WW03 2018). At that time, you will find `INTEL_CHAINER_ROOT/ideep4py` for `iDeep` package.

Thanks.

**Comment by niboshi** [comment]
OK, thank you for clarification.
Do you have any rough estimation on how long internal approval could take?

**Comment by fengyuan14** [comment]
We try and drive to finish Intel internal approval process by the end of next week (WW04 2018). We will inform you timely,  if it is done.

Thanks.

**Comment by niboshi** [comment]
@arthuryuan1987 
OK, thank you very much!

**Comment by fengyuan14** [comment]
What about rest operations/functions or other optimizations, like SGD, that `iDeep` supports ? Do you have plan to integrate them by yourselves ? or let us provide pull request for them ?

If you have plan to integrate them by yourselves, we will provide bugs or other optimization details we met during `iDeep` integration in Intel Chainer to you. Of course, you could reference Intel Chainer (new release in this week), branch `master_v3`, to take a look at our work as well.

**Comment by niboshi** [comment]
Thank you the suggestions in this PR.
As basic iDeep integration and function implementations has been merged in Chainer master branch, I close this PR now.
We appreciate all the help for this work. Let's keep contact on Slack or other channel for further discussions!

**Pull request closed without merging**
